language: go

env:
  - GO111MODULE=on

go:
  - 1.x

before_install:
  - go get -t -v ./...

script:
  - go test ./... -race
  - go test ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
