// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/network/ambassador.go

// Package network is a generated GoMock package.
package network

import (
	gomock "github.com/golang/mock/gomock"
	events "github.com/nuts-foundation/nuts-registry/pkg/events"
	reflect "reflect"
)

// MockAmbassador is a mock of Ambassador interface
type MockAmbassador struct {
	ctrl     *gomock.Controller
	recorder *MockAmbassadorMockRecorder
}

// MockAmbassadorMockRecorder is the mock recorder for MockAmbassador
type MockAmbassadorMockRecorder struct {
	mock *MockAmbassador
}

// NewMockAmbassador creates a new mock instance
func NewMockAmbassador(ctrl *gomock.Controller) *MockAmbassador {
	mock := &MockAmbassador{ctrl: ctrl}
	mock.recorder = &MockAmbassadorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAmbassador) EXPECT() *MockAmbassadorMockRecorder {
	return m.recorder
}

// RegisterEventHandlers mocks base method
func (m *MockAmbassador) RegisterEventHandlers(fn events.EventRegistrar, eventType []events.EventType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterEventHandlers", fn, eventType)
}

// RegisterEventHandlers indicates an expected call of RegisterEventHandlers
func (mr *MockAmbassadorMockRecorder) RegisterEventHandlers(fn, eventType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterEventHandlers", reflect.TypeOf((*MockAmbassador)(nil).RegisterEventHandlers), fn, eventType)
}
