version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    environment:
      GO111MODULE: "on"

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run: go get -t -v ./...

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run: go test ./... -race

      - run: go test ./... -coverprofile=coverage.txt -covermode=atomic -v

      - run: bash <(curl -s https://codecov.io/bash)
